// ===== Daily quotes =====
const QUOTES = [
    'Do the thing you keep putting off.',
    'Small steps every day.',
    'Focus is a superpower.',
    'Done is better than perfect.',
    'Make today count.',
    'Progress, not perfection.',
    'One task at a time.',
    'Start where you are.',
    'Discipline equals freedom.',
    'The work is the reward.',
    'Slow is smooth, smooth is fast.',
    'You have time for what matters.',
    'Less noise, more signal.',
    'Show up. That is most of it.',
    // Action & Starting
    'Action cures fear.',
    'Begin anywhere.',
    'Just start.',
    'Take the first step.',
    'Motion beats meditation.',
    'Do what you can.',
    'Move the needle.',
    'Create momentum.',
    'Do not wait for inspiration.',
    'Execute on the idea.',
    'Make it happen.',
    'Act before you are ready.',
    'Momentum is magic.',
    'Put in the reps.',
    'Talk less, do more.',
    'Actions express priority.',
    'Do it badly, but do it.',
    'Start small, think big.',
    'Keep moving forward.',
    'Inertia is the enemy.',
    'Decide and act.',
    'Do the hard thing first.',
    'Eat the frog.',
    'Bias toward action.',
    'Hesitation kills progress.',
    'Action is the foundational key.',
    'Start before you feel ready.',
    'The time is now.',
    'Do not overthink it.',
    'Build it as you fly.',
    'Take massive action.',
    'Do the work.',
    'Stop planning, start doing.',
    'Leap and the net will appear.',
    'Action is the best teacher.',
    'Be a maker.',
    'Ship it.',
    'Do not wait for tomorrow.',
    'Make your own luck.',
    'Initiative is everything.',
    'Strike the match.',
    'Action precedes motivation.',
    'Get out of your own way.',
    'Dive in.',
    'Commit and figure it out.',
    'Turn intention into action.',
    'Cross the starting line.',
    'Do something today.',
    'Effort is a choice.',
    'Show your work.',

    // Focus & Attention
    'Ignore the noise.',
    'Protect your attention.',
    'Do one thing well.',
    'Starve distractions.',
    'Feed your focus.',
    'Keep the main thing the main thing.',
    'Say no to almost everything.',
    'Deep work matters.',
    'Focus is a choice.',
    'Where attention goes, energy flows.',
    'Eliminate the non-essential.',
    'Unplug to connect.',
    'Multitasking is a myth.',
    'Guard your time.',
    'Clarity over speed.',
    'Silence the notifications.',
    'Direction is more important than speed.',
    'Focus on the step, not the mountain.',
    'Be here now.',
    'Distraction is the death of art.',
    'Look at what matters.',
    'Zoom in.',
    'Subtract the obvious.',
    'Add the meaningful.',
    'Attention is your greatest asset.',
    'One screen at a time.',
    'Focus creates reality.',
    'Block out the world.',
    'Choose your focus.',
    'Stay in your lane.',
    'Bore down on the task.',
    'Keep your eyes on the prize.',
    'Ruthless prioritization.',
    'Clear your desk, clear your mind.',
    'Protect your peace.',
    'Focus is saying no.',
    'Master your attention.',
    'Do it with purpose.',
    'Give it your full self.',
    'Stop scrolling, start creating.',
    'Be ruthlessly focused.',
    'Avoid the shiny objects.',
    'Stay the course.',
    'A narrow focus brings broad results.',
    'Center yourself.',
    'Zero in on the target.',
    'Defend your flow state.',
    'Concentration is power.',
    'Do not scatter your energy.',
    'Focus on what you can control.',

    // Discipline & Consistency
    'Consistency beats intensity.',
    'Show up every day.',
    'Build the habit.',
    'Never miss twice.',
    'Drop by drop fills the bucket.',
    'Routine sets you free.',
    'Do it especially when you do not want to.',
    'Repetition is the mother of skill.',
    'Keep the streak alive.',
    'Patience and persistence.',
    'Brick by brick.',
    'Habits compound over time.',
    'Trust the process.',
    'Fall in love with boredom.',
    'Stay in the game.',
    'Endurance wins the race.',
    'Be aggressively patient.',
    'Outlast the critics.',
    'Keep chopping wood.',
    'Carry the water.',
    'Consistency is the ultimate hack.',
    'Do not break the chain.',
    'Little by little becomes a lot.',
    'Play the long game.',
    'Commit to the long term.',
    'Small daily gains.',
    'Discipline bridges the gap.',
    'Routines remove resistance.',
    'Be undeniably consistent.',
    'Weather the storm.',
    'Keep your promises to yourself.',
    'Show up for yourself.',
    'It adds up.',
    'Time in the market beats timing the market.',
    'Stay on the path.',
    'Do the daily work.',
    'Results follow consistency.',
    'Master the mundane.',
    'Do not quit on a bad day.',
    'Forge the habit.',
    'Repetition breeds mastery.',
    'Every day is day one.',
    'Pace yourself.',
    'Keep laying bricks.',
    'Outwork your yesterday.',
    'Discipline over motivation.',
    'The magic is in the daily routine.',
    'Consistent action creates consistent results.',
    'Do it again.',
    'Keep pushing.',

    // Overcoming Perfectionism & Completion
    'Good enough is good enough.',
    'Perfect is the enemy of good.',
    'Finished is beautiful.',
    'Launch it ugly.',
    'Iterate, iterate, iterate.',
    'Embrace the messy middle.',
    'You can edit a bad page.',
    'You cannot edit a blank page.',
    'Volume precedes quality.',
    'Let go of perfect.',
    'Done clears the mind.',
    'Finish what you start.',
    'Fail fast, learn faster.',
    'Your first draft will suck.',
    'Progress requires failure.',
    'Stop tweaking.',
    'Hit publish.',
    'Put it out there.',
    'Completion over perfection.',
    'Learn by doing.',
    'Embrace constraints.',
    'Deadlines are magic.',
    'Version one is better than version none.',
    'Make mistakes quickly.',
    'Ship the work.',
    'Art is never finished, only abandoned.',
    'Do not let perfect ruin good.',
    'Accept the flaws.',
    'Refine it later.',
    'Release the pressure.',
    'Celebrate the finish line.',
    'Drafts are meant to be dirty.',
    'Cross it off the list.',
    'Close the loop.',
    'Endings are just beginnings.',
    'Do not polish a rough draft.',
    'Get it on paper.',
    'Allow yourself to be a beginner.',
    'There is no perfect time.',
    'There is no perfect plan.',
    'Act > Perfect.',
    'Do not overcook it.',
    'Let the work breathe.',
    'The world needs your rough draft.',
    'Strive for excellence, not perfection.',
    'Embrace the process of becoming.',
    'Quantity leads to quality.',
    'Tolerate imperfection.',
    'Deliver the goods.',
    'Check the box.',

    // Simplicity & Minimalism
    'Keep it simple.',
    'Less is more.',
    'Simplify your life.',
    'Cut the clutter.',
    'Remove the friction.',
    'Subtract until it breaks.',
    'Clarity is power.',
    'Declutter your mind.',
    'Essentialism is key.',
    'Do less, but better.',
    'Optimize for simplicity.',
    'Avoid the complex.',
    'Find the elegant solution.',
    'Strip away the inessential.',
    'Protect your whitespace.',
    'Make it easy.',
    'Reduce the steps.',
    'Keep the overhead low.',
    'Live lightly.',
    'Clear space, clear mind.',
    'Only keep what serves you.',
    'Automate the routine.',
    'Delegate the rest.',
    'Find the shortest path.',
    'Say no to extra features.',
    'Master the basics.',
    'Fundamentals first.',
    'A confused mind says no.',
    'Keep the rules simple.',
    'Less baggage, more speed.',
    'Edit your life.',
    'Trim the fat.',
    'Seek quiet.',
    'Less stress, more success.',
    'Curate your inputs.',
    'Protect your bandwidth.',
    'Stop adding, start subtracting.',
    'Value space over stuff.',
    'Simplicity scales.',
    'Complexity fails.',
    'Focus on the core.',
    'Embrace the minimalist mindset.',
    'Travel light.',
    'Make room for what matters.',
    'Do not complicate it.',
    'The simple way is the hard way.',
    'Seek clarity above all.',
    'Quiet the mind.',
    'Rest is productive.',
    'Breathe.',

    // Mindset & Resilience
    'Obstacles are the way.',
    'Embrace the suck.',
    'Growth happens outside comfort.',
    'Be your own rescue.',
    'Mind over matter.',
    'Choose your attitude.',
    'You are what you repeatedly do.',
    'Take extreme ownership.',
    'No excuses.',
    'Victimhood is a trap.',
    'Focus on the solution.',
    'Pain is temporary.',
    'Quitting lasts forever.',
    'Hard choices, easy life.',
    'Easy choices, hard life.',
    'Be antifragile.',
    'Fail forward.',
    'Learn from the losses.',
    'Keep your head down.',
    'Stay humble.',
    'Do the work in the dark.',
    'Let your results talk.',
    'Confidence comes from competence.',
    'Believe in your capacity.',
    'Comparison is the thief of joy.',
    'Run your own race.',
    'You are enough.',
    'Doubt kills more dreams than failure.',
    'Be fiercely independent.',
    'Adapt and overcome.',
    'Seek discomfort.',
    'Toughen up.',
    'Control your emotions.',
    'Respond, do not react.',
    'Be a student of reality.',
    'Your perspective is your reality.',
    'Protect your energy.',
    'Gratitude grounds you.',
    'Stay hungry.',
    'Stay foolish.',
    'Rejection is redirection.',
    'Thrive under pressure.',
    'Turn pain into power.',
    'The mind is the limit.',
    'Choose courage over comfort.',
    'Stand firm.',
    'Be a force of nature.',
    'Expect nothing, appreciate everything.',
    'Your mind is a weapon.',
    'Keep the fire burning.',

    // Time & Priorities
    'Time is your only currency.',
    'Spend time, do not kill it.',
    'Prioritize ruthlessly.',
    'First things first.',
    'Tomorrow is a myth.',
    'Own your morning.',
    'Win the morning, win the day.',
    'Time blocks work.',
    'Manage your energy, not time.',
    'The future is built today.',
    'Saying yes to one thing is saying no to another.',
    'Value your time, others will too.',
    'Do not major in minor things.',
    'Urgent is rarely important.',
    'Important is rarely urgent.',
    'Audit your time.',
    'Schedule your priorities.',
    'Life is short, do the work.',
    'Maximize the present moment.',
    'Make it count.',
    'Every minute matters.',
    'Invest your hours.',
    'Create before you consume.',
    'Protect your peak hours.',
    'Now is all you have.'
];
